#!/usr/bin/python
import sys
sys.path.insert(0, "..")

"""
Author: Eltjon Metko
Problem 2
------------------------------------------------------------------------------
Each new term in the Fibonacci sequence
is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence
whose values do not exceed four million,
find the sum of the even-valued terms.
------------------------------------------------------------------------------
"""
from utils.misc import *


def euler_002(MAX_NUM=4000000):
    return sum(x for x in itertools.takewhile(lambda a: a < MAX_NUM, fib_gen())
                  if x % 2)

if __name__ == '__main__':
    print(euler_002())
